### ISSUE TITLE
Issue with jupyter notebook kernel dies when running `optimize` function on Dogs and Cats example chapter 3 

### ISSUE THREAD

**Issue by 00krishna** [PacktPublishing/Practical-Convolutional-Neural-Networks#1]
So I created a jupyter notebook in an nvidia docker container that has tensorflow and keras, as well as the Cuda libraries. The code from the Dogs and Cats example seems to go in okay, but when I run the code

`optimize(num_iterations=10000)`

I get a message from jupyter notebook saying that the kernel has died. It looks like the optimize function is still running, but I have a message saying that the "kernel had died." But the notebook still shows the dark circle in the upper right, suggesting that the kernel is still computing. 

Did the kernel really die, or is this just a dummy message that occurs while the model is computing?

![selection_003](https://user-images.githubusercontent.com/2063593/40291175-1b2c0158-5c78-11e8-8ec8-93ec8051063a.png)

Here is what the notebook looks like after I click off on the dialog box. It is still indicating no kernel.

![selection_002](https://user-images.githubusercontent.com/2063593/40291177-231c1092-5c78-11e8-99e5-b831441650ee.png)

**Comment by rezacsedu** [comment]
@00krishna your machine has to have enough RAM and processing power preferably GPU to process and finish the training. 

When I wrote this script, I tested the code on my laptop having 32GB of RAM, Core i7 processor, and Nvidia 1050i GPU and I didn't experience such issue. 

Alternatively, try training with a few hundreds of images.
