### ISSUE TITLE
Practical Example Image Classification Code Issue

### ISSUE THREAD

**Issue by mark-bragg** [PacktPublishing/Practical-Convolutional-Neural-Networks#2]
**Code that is causing the issue in Chapter 2 CNN_2.py:**
```
import keras
import numpy as np
import matplotlib.pyplot as plt
%matplotlib 
inlinefig = plt.figure(figsize=(20,5))
for i in range(36):
    ax = fig.add_subplot(3, 12, i + 1, xticks=[], yticks=[])
    ax.imshow(np.squeeze(x_train[i]))from keras.datasets import cifar10
```

**Error that is being thrown:**
`  File "<ipython-input-3-bd39b7db8dbc>", line 9
    ax.imshow(np.squeeze(x_train[i]))from keras.datasets import cifar10
                                        ^
SyntaxError: invalid syntax`

**Suggested Fix:**
```
from keras.datasets import cifar10
(x_train, y_train), (x_test, y_test) = cifar10.load_data()
```

**Comment by utkarsha-Packt** [comment]
Please try the following syntax:

from keras.datasets import cifar10
(x_train, y_train), (x_test, y_test) = cifar10.load_data()
